# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapONNTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapONNTest
  pod 'SDWebImage', '~> 5.0'
  pod 'Cosmos', '~> 22.1'
end
